### ISSUE TITLE
Batches do not generate properly

### ISSUE THREAD

**Issue by NikkMann** [xrpgame/xyz_plot_script#3]
As stated, trying to generate batches with batch count causes it to lose/not keep every image except for the first one in the batch.
In the normal X/Y script it keeps and displays all extra batches

**Comment by NikkMann** [comment]
Seems like batch size also does not work at all, the script will always only keep 1 image per X/Y/Z coordinate.
If you could get batches working like they do in the normal X/Y script, your script would be a godsend

**Comment by zer0TF** [comment]
Batch size and batch num parameters are hard-coded to a value of `1`. Changing these is not currently supported. This is because the number of images generated is dictated by the X+Y+Z axes.

For example, if you have 3 CFG Scale parameters, 2 hypernetworks, and 4 checkpoints, this script will generate 3*2*4=24 images. Supporting batches would mean supporting an extra "dimension" which we can't currently display in the UI that gets output (i.e. in this example, batch size of 2 means 24 * 2 = 48 images, the web viewer does not have a way to visualize this 
"fourth dimension").

You can use Seed as a parameter if you want to generate multiple images, similar to a batch. Just specify seed as one dimension, and add the seed value sequentially. So if your seed is 45000 and you normally use a batch size of 4, you would enter `45000,45001,45002,45003` as your seed dimension value.

**Comment by NikkMann** [comment]
> Batch size and batch num parameters are hard-coded to a value of `1`. Changing these is not currently supported. This is because the number of images generated is dictated by the X+Y+Z axes.
> 
> For example, if you have 3 CFG Scale parameters, 2 hypernetworks, and 4 checkpoints, this script will generate 3_2_4=24 images. Supporting batches would mean supporting an extra "dimension" which we can't currently display in the UI that gets output (i.e. in this example, batch size of 2 means 24 * 2 = 48 images, the web viewer does not have a way to visualize this "fourth dimension").
> 
> You can use Seed as a parameter if you want to generate multiple images, similar to a batch. Just specify seed as one dimension, and add the seed value sequentially. So if your seed is 45000 and you normally use a batch size of 4, you would enter `45000,45001,45002,45003` as your seed dimension value.

Wanna preface this by saying I'm not trying to argue or come off as angry, cause I realize what I typed sounds that way after reading it back lol.

The explanation doesn't really make sense because in the normal X/Y script, you can use both batch image and batch count at the same time, which by your logic would add a Z axis and another (W?) 4th axis. But thats not what it does. It renders all the batch images, then puts them together and displays all of them in a grid as "one image" on the X/Y plot for that X and Y value.
And in your script, if I put the batch count up, it takes alot longer to render, which shows that it is actually creating the images in the background, but its just throwing them away instead of stitching them together like the normal X/Y script does.

Here is what the normal X/Y script outputs with a batch count of 4 AND a batch size of 4, so each "point" on the X/Y plot is generating 16 images and then tiling all of them into 1 image while keeping all of their original resolutions (so you get one ridiculously high-res image at the end): 
Had to upload to google drive because it was too big for image hosting sites lol:
https://drive.google.com/file/d/1BbZ5hF0LAw_UNuZsasFiu7GrhcbuZJX2/view?usp=sharing

As for your suggestion to make the Batch a pseudo-z Axis argument by having variations for Seeds, well that kind of defeats the purpose of your script because I can have actual batches in the normal X/Y script and have all of them tiled together on 1 large image instead of having to scroll through several "z axis" images.

I was hoping to use your script to get a large sample size comparison between different samplers (z axis) at different Step (x) and CFG (y) values. And the best (and fastest) way to get a large sample size is with batches.

**Comment by NikkMann** [comment]
Any luck with this or is it just gonna be left as is?
