### ISSUE TITLE
Is it possible to bring this script more inline with standard x/y plot?

### ISSUE THREAD

**Issue by PZAragon** [xrpgame/xyz_plot_script#6]
_Is it possible to bring this script more inline with standard x/y plot?_
By that I mean:
1) Generate file names using the WebUI configuration (patterns, etc)
2) Save images in the directories configured in the WebUI
2) Follow the "batch count" field. It would be great if it would also follow the batch size, but the standard x/y script also ignores batch size.

I posted a longer explanation here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/3775

**Comment by zer0TF** [comment]
1. Images can't easily be fed into the .html viewer if the naming isn't consistent. Yes, it could be done via a mapping, but I'm not sure if the way I save the images is compatible with the custom naming templates. I would accept a PR from someone if this were able to be figured out without breaking anything.
2. We do respect the image output directory. Since we don't produce "grids" in the traditional sense, we don't write to that directory. 🙂
3. Batch count and batch size are both used to produce multiple images. It does so by simply incrementing the seed by one (at least for batch size). So this concept is not compatible with the X/Y or X/Y/Z grid scripts, because each axis already has multiple images on it. Batch count and size are effectively a "fourth dimension". If you want the same behavior, just set one of your axes to be "Seed", and increment the seed by one (e.g. 100,101,102,103). This is the same as "batch size = 4".
